objects:
  - uuid: '%role.administrator.uuid%'
    title:
      en: Administrator
    slug: administrator
    permissions:
      assets:
        - scope:
            type: owner
            entity: BusinessUnit
            entityUuid: '%business_unit.administration.uuid%'
          permissions:
            - key: entity
              attributes: [BROWSE, READ, EDIT, ADD, DELETE]
            - key: property
              attributes: [BROWSE, READ, EDIT]
        - scope:
            type: generic
          permissions:
            - key: generic
              attributes: [BROWSE, READ, EDIT, ADD, DELETE, EXECUTE]
      authentication:
        - scope:
            type: owner
            entity: BusinessUnit
            entityUuid: '%business_unit.administration.uuid%'
          permissions:
            - key: entity
              attributes: [BROWSE, READ, EDIT, ADD, DELETE]
            - key: property
              attributes: [BROWSE, READ, EDIT]
        - scope:
            type: generic
          permissions:
            - key: generic
              attributes: [BROWSE, READ, EDIT, ADD, DELETE, EXECUTE]
      cases:
        - scope:
            type: owner
            entity: BusinessUnit
            entityUuid: '%business_unit.administration.uuid%'
          permissions:
            - key: entity
              attributes: [BROWSE, READ, EDIT, ADD, DELETE]
            - key: property
              attributes: [BROWSE, READ, EDIT]
        - scope:
            type: generic
          permissions:
            - key: generic
              attributes: [BROWSE, READ, EDIT, ADD, DELETE, EXECUTE]
      cms:
        - scope:
            type: owner
            entity: BusinessUnit
            entityUuid: '%business_unit.administration.uuid%'
          permissions:
            - key: entity
              attributes: [BROWSE, READ, EDIT, ADD, DELETE]
            - key: property
              attributes: [BROWSE, READ, EDIT]
        - scope:
            type: generic
          permissions:
            - key: generic
              attributes: [BROWSE, READ, EDIT, ADD, DELETE, EXECUTE]
      forms:
        - scope:
            type: owner
            entity: BusinessUnit
            entityUuid: '%business_unit.administration.uuid%'
          permissions:
            - key: entity
              attributes: [BROWSE, READ, EDIT, ADD, DELETE]
            - key: property
              attributes: [BROWSE, READ, EDIT]
        - scope:
            type: generic
          permissions:
            - key: generic
              attributes: [BROWSE, READ, EDIT, ADD, DELETE, EXECUTE]
      identities:
        - scope:
            type: owner
            entity: BusinessUnit
            entityUuid: '%business_unit.administration.uuid%'
          permissions:
            - key: entity
              attributes: [BROWSE, READ, EDIT, ADD, DELETE]
            - key: property
              attributes: [BROWSE, READ, EDIT]
        - scope:
            type: generic
          permissions:
            - key: generic
              attributes: [BROWSE, READ, EDIT, ADD, DELETE, EXECUTE]
      records:
        - scope:
            type: owner
            entity: BusinessUnit
            entityUuid: '%business_unit.administration.uuid%'
          permissions:
            - key: entity
              attributes: [BROWSE, READ, EDIT, ADD, DELETE]
            - key: property
              attributes: [BROWSE, READ, EDIT]
        - scope:
            type: generic
          permissions:
            - key: generic
              attributes: [BROWSE, READ, EDIT, ADD, DELETE, EXECUTE]
      services:
        - scope:
            type: owner
            entity: BusinessUnit
            entityUuid: '%business_unit.administration.uuid%'
          permissions:
            - key: entity
              attributes: [BROWSE, READ, EDIT, ADD, DELETE]
            - key: property
              attributes: [BROWSE, READ, EDIT]
        - scope:
            type: generic
          permissions:
            - key: generic
              attributes: [BROWSE, READ, EDIT, ADD, DELETE, EXECUTE]
      tasks:
        - scope:
            type: owner
            entity: BusinessUnit
            entityUuid: '%business_unit.administration.uuid%'
          permissions:
            - key: entity
              attributes: [BROWSE, READ, EDIT, ADD, DELETE]
            - key: property
              attributes: [BROWSE, READ, EDIT]
        - scope:
            type: generic
          permissions:
            - key: generic
              attributes: [BROWSE, READ, EDIT, ADD, DELETE, EXECUTE]
      tenants:
        - scope:
            type: owner
            entity: BusinessUnit
            entityUuid: '%business_unit.administration.uuid%'
          permissions:
            - key: entity
              attributes: [BROWSE, READ, EDIT, ADD, DELETE]
            - key: property
              attributes: [BROWSE, READ, EDIT]
        - scope:
            type: generic
          permissions:
            - key: generic
              attributes: [BROWSE, READ, EDIT, ADD, DELETE, EXECUTE]

prototype:
  uuid: ~
  owner: BusinessUnit
  owner_uuid: '%business_unit.administration.uuid%'
  title: {}
  slug: ~
  permissions: {}
  tenant: '%tenant.uuid%'
