parameters:
  env(VARNISH_URL): ''

api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  title: Identities
  version: 0.19.0
  collection:
    pagination:
      page_parameter_name: _page
      items_per_page_parameter_name: _limit
      client_items_per_page: true
      items_per_page: 10
      maximum_items_per_page: 100
  http_cache:
    invalidation:
      enabled: false
    max_age: 0
    shared_max_age: 3600
    vary: ['Content-Type', 'Authorization']
    public: true

services:
  app.filter.anonymous.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
    tags:
      - { name: api_platform.filter, id: app.anonymous.search }

  app.filter.anonymous.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
        deletedAt: ~
    tags:
      - { name: api_platform.filter, id: app.anonymous.date }

  app.filter.anonymous.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        deletedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.anonymous.order }

  app.filter.anonymous_persona.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
    tags:
      - { name: api_platform.filter, id: app.anonymous_persona.search }

  app.filter.anonymous_persona.search_translation:
    parent: ds_translation.doctrine.orm.filter.search
    arguments:
      - title: ipartial
    tags:
      - { name: api_platform.filter, id: app.anonymous_persona.search_translation }

  app.filter.anonymous_persona.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
        deletedAt: ~
    tags:
      - { name: api_platform.filter, id: app.anonymous_persona.date }

  app.filter.anonymous_persona.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        deletedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.anonymous_persona.order }
          
  app.filter.anonymous_role.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        anonymous.uuid: exact
        role.uuid: exact
    tags:
      - { name: api_platform.filter, id: app.anonymous_role.search }

  app.filter.anonymous_role.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
    tags:
      - { name: api_platform.filter, id: app.anonymous_role.date }

  app.filter.anonymous_role.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.anonymous_role.order }

  app.filter.business_unit.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
    tags:
      - { name: api_platform.filter, id: app.business_unit.search }

  app.filter.business_unit.search_translation:
    parent: ds_translation.doctrine.orm.filter.search
    arguments:
      - title: ipartial
    tags:
      - { name: api_platform.filter, id: app.business_unit.search_translation }

  app.filter.business_unit.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
        deletedAt: ~
    tags:
      - { name: api_platform.filter, id: app.business_unit.date }

  app.filter.business_unit.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        deletedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.business_unit.order }

  app.filter.business_unit_role.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        businessUnit.uuid: exact
        businessUnit.staffs.uuid: exact
        role.uuid: exact
    tags:
      - { name: api_platform.filter, id: app.business_unit_role.search }

  app.filter.business_unit_role.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
    tags:
      - { name: api_platform.filter, id: app.business_unit_role.date }

  app.filter.business_unit_role.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.business_unit_role.order }

  app.filter.individual.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
    tags:
      - { name: api_platform.filter, id: app.individual.search }

  app.filter.individual.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
        deletedAt: ~
    tags:
      - { name: api_platform.filter, id: app.individual.date }

  app.filter.individual.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        deletedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.individual.order }

  app.filter.individual_persona.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        individual.uuid: exact
    tags:
      - { name: api_platform.filter, id: app.individual_persona.search }

  app.filter.individual_persona.search_translation:
    parent: ds_translation.doctrine.orm.filter.search
    arguments:
      - title: ipartial
    tags:
      - { name: api_platform.filter, id: app.individual_persona.search_translation }

  app.filter.individual_persona.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
        deletedAt: ~
    tags:
      - { name: api_platform.filter, id: app.individual_persona.date }

  app.filter.individual_persona.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        deletedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.individual_persona.order }

  app.filter.individual_role.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        individual.uuid: exact
        role.uuid: exact
    tags:
      - { name: api_platform.filter, id: app.individual_role.search }

  app.filter.individual_role.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
    tags:
      - { name: api_platform.filter, id: app.individual_role.date }

  app.filter.individual_role.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.individual_role.order }

  app.filter.organization.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
    tags:
      - { name: api_platform.filter, id: app.organization.search }

  app.filter.organization.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
        deletedAt: ~
    tags:
      - { name: api_platform.filter, id: app.organization.date }

  app.filter.organization.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        deletedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.organization.order }

  app.filter.organization_persona.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        organization.uuid: exact
    tags:
      - { name: api_platform.filter, id: app.organization_persona.search }

  app.filter.organization_persona.search_translation:
    parent: ds_translation.doctrine.orm.filter.search
    arguments:
      - title: ipartial
    tags:
      - { name: api_platform.filter, id: app.organization_persona.search_translation }

  app.filter.organization_persona.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
        deletedAt: ~
    tags:
      - { name: api_platform.filter, id: app.organization_persona.date }

  app.filter.organization_persona.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        deletedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.organization_persona.order }

  app.filter.organization_role.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        organization.uuid: exact
        role.uuid: exact
    tags:
      - { name: api_platform.filter, id: app.organization_role.search }

  app.filter.organization_role.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
    tags:
      - { name: api_platform.filter, id: app.organization_role.date }

  app.filter.organization_role.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.organization_role.order }

  app.filter.role.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        slug: exact
    tags:
      - { name: api_platform.filter, id: app.role.search }

  app.filter.role.search_translation:
    parent: ds_translation.doctrine.orm.filter.search
    arguments:
      - title: ipartial
    tags:
      - { name: api_platform.filter, id: app.role.search_translation }

  app.filter.role.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
        deletedAt: ~
    tags:
      - { name: api_platform.filter, id: app.role.date }

  app.filter.role.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        deletedAt: ~
        owner: ~
        slug: ~
    tags:
      - { name: api_platform.filter, id: app.role.order }

  app.filter.staff.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        businessUnits.uuid: exact
    tags:
      - { name: api_platform.filter, id: app.staff.search }

  app.filter.staff.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
        deletedAt: ~
    tags:
      - { name: api_platform.filter, id: app.staff.date }

  app.filter.staff.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        deletedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.staff.order }

  app.filter.staff_persona.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        staff.uuid: exact
    tags:
      - { name: api_platform.filter, id: app.staff_persona.search }

  app.filter.staff_persona.search_translation:
    parent: ds_translation.doctrine.orm.filter.search
    arguments:
      - title: ipartial
    tags:
      - { name: api_platform.filter, id: app.staff_persona.search_translation }

  app.filter.staff_persona.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
        deletedAt: ~
    tags:
      - { name: api_platform.filter, id: app.staff_persona.date }

  app.filter.staff_persona.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        deletedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.staff_persona.order }

  app.filter.staff_role.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        staff.uuid: exact
        role.uuid: exact
    tags:
      - { name: api_platform.filter, id: app.staff_role.search }

  app.filter.staff_role.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
    tags:
      - { name: api_platform.filter, id: app.staff_role.date }

  app.filter.staff_role.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.staff_role.order }

  app.filter.system.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
    tags:
      - { name: api_platform.filter, id: app.system.search }

  app.filter.system.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
        deletedAt: ~
    tags:
      - { name: api_platform.filter, id: app.system.date }

  app.filter.system.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        deletedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.system.order }

  app.filter.system_role.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        system.uuid: exact
        role.uuid: exact
    tags:
      - { name: api_platform.filter, id: app.system_role.search }

  app.filter.system_role.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
    tags:
      - { name: api_platform.filter, id: app.system_role.date }

  app.filter.system_role.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
        owner: ~
    tags:
      - { name: api_platform.filter, id: app.system_role.order }
