parameters:
    _system: Ds\Bundle\SystemBundle\Entity\System

ds_security:
    permissions:
        system:               { title: System,         entity: '%_system%',              attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        system_field:         { title: All Fields,    field:  '%_system%.*',            attributes: [BROWSE, READ, EDIT] }
        system_id:            { title: ID,            field:  '%_system%.id',           attributes: [BROWSE, READ, EDIT] }
        system_uuid:          { title: UUID,          field:  '%_system%.uuid',         attributes: [BROWSE, READ, EDIT] }
        system_created_at:    { title: Created At,    field:  '%_system%.createdAt',    attributes: [BROWSE, READ, EDIT] }
        system_updated_at:    { title: Updated At,    field:  '%_system%.updatedAt',    attributes: [BROWSE, READ, EDIT] }
        system_deleted_at:    { title: Deleted At,    field:  '%_system%.deletedAt',    attributes: [BROWSE, READ, EDIT] }
        system_owner:         { title: Owner,         field:  '%_system%.owner',        attributes: [BROWSE, READ, EDIT] }
        system_owner_uuid:    { title: Owner UUID,    field:  '%_system%.ownerUuid',    attributes: [BROWSE, READ, EDIT] }
