services:
    ds_system.service.system:
        class: Ds\Bundle\SystemBundle\Service\SystemService

    ds_system.filter.system:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            - { uuid: exact }
        tags:
            - { name: api_platform.filter, id: ds_system.filter.system }
