api:
    resource: .
    type: api_platform

ds_security:
    resource: "@DsSecurityBundle/Resources/config/routing.yml"

#ds_business_unit:
#    resource: "@DsBusinessUnitBundle/Action/"
#    type: annotation

#ds_individual:
#    resource: "@DsIndividualBundle/Action/"
#    type: annotation
