security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            stateless: true
            anonymous: true
            provider: jwt
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/security/permissions, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/accesses,             role: IS_AUTHENTICATED_FULLY }
        - { path: ^/configs,              role: IS_AUTHENTICATED_FULLY }
        - { path: ^/business-units,       role: IS_AUTHENTICATED_FULLY }
        - { path: ^/admins,               role: IS_AUTHENTICATED_FULLY }
        - { path: ^/systems,              role: IS_AUTHENTICATED_FULLY }
        - { path: ^/staffs,               role: IS_AUTHENTICATED_FULLY }
        - { path: ^/staff-personas,       role: IS_AUTHENTICATED_FULLY }
        - { path: ^/individuals,          role: IS_AUTHENTICATED_FULLY }
        - { path: ^/individual-personas,  role: IS_AUTHENTICATED_FULLY }
        - { path: ^/anonymouses,          role: IS_AUTHENTICATED_FULLY }
        - { path: ^/anonymous-personas,   role: IS_AUTHENTICATED_FULLY }
