objects:
  - uuid: '%business_unit.administration.uuid%'
    title:
      en: Administration

prototype:
  uuid: ~
  owner: BusinessUnit
  owner_uuid: '%business_unit.administration.uuid%'
  title: {}
  version: 1
  tenant: '%tenant.uuid%'
