services:
    app.event_listener.role.permissions:
        class: AppBundle\EventListener\Role\PermissionsListener
        arguments:
            - '@service_container'
        tags:
            - { name: doctrine.orm.entity_listener, entity: AppBundle\Entity\Role, event: postPersist }
