services:
    app.service.admin:
        class: AppBundle\Service\AdminService
        parent: ds_entity.service.entity

    app.service.anonymous:
        class: AppBundle\Service\AnonymousService
        parent: ds_entity.service.entity

    app.service.anonymous_persona:
        class: AppBundle\Service\AnonymousPersonaService
        parent: ds_entity.service.entity

    app.service.business_unit:
        class: AppBundle\Service\BusinessUnitService
        parent: ds_entity.service.entity

    app.service.individual:
        class: AppBundle\Service\IndividualService
        parent: ds_entity.service.entity

    app.service.individual_persona:
        class: AppBundle\Service\IndividualPersonaService
        parent: ds_entity.service.entity

    app.service.staff:
        class: AppBundle\Service\StaffService
        parent: ds_entity.service.entity

    app.service.staff_persona:
        class: AppBundle\Service\StaffPersonaService
        parent: ds_entity.service.entity

    app.service.system:
        class: AppBundle\Service\SystemService
        parent: ds_entity.service.entity
