services:
  app.service.anonymous:
    class: AppBundle\Service\AnonymousService
    arguments:
      - '@doctrine.orm.entity_manager'

  app.service.anonymous_persona:
    class: AppBundle\Service\AnonymousPersonaService
    arguments:
      - '@doctrine.orm.entity_manager'

  app.service.business_unit:
    class: AppBundle\Service\BusinessUnitService
    arguments:
      - '@doctrine.orm.entity_manager'

  app.service.individual:
    class: AppBundle\Service\IndividualService
    arguments:
      - '@doctrine.orm.entity_manager'

  app.service.individual_persona:
    class: AppBundle\Service\IndividualPersonaService
    arguments:
      - '@doctrine.orm.entity_manager'

  app.service.organization:
    class: AppBundle\Service\OrganizationService
    arguments:
      - '@doctrine.orm.entity_manager'

  app.service.organization_persona:
    class: AppBundle\Service\OrganizationPersonaService
    arguments:
      - '@doctrine.orm.entity_manager'

  app.service.role:
    class: AppBundle\Service\RoleService
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@ds_security.service.access'
      - '@ds_security.service.permission'
      - '@ds_api.api'

  app.service.staff:
    class: AppBundle\Service\StaffService
    arguments:
      - '@doctrine.orm.entity_manager'

  app.service.staff_persona:
    class: AppBundle\Service\StaffPersonaService
    arguments:
      - '@doctrine.orm.entity_manager'

  app.service.system:
    class: AppBundle\Service\SystemService
    arguments:
      - '@doctrine.orm.entity_manager'
