ds_security:
    acl:
        permissions:
            business_unit:             { entity: Ds\Bundle\BusinessUnitBundle\Entity\BusinessUnit, attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
            business_unit_field:       { field:  Ds\Bundle\BusinessUnitBundle\Entity\BusinessUnit.*, attributes: [BROWSE, READ, EDIT] }
