services:
    ds_business_unit.service.business_unit:
        class: Ds\Bundle\BusinessUnitBundle\Service\BusinessUnitService
        arguments:
            - '@doctrine.orm.entity_manager'
            - Ds\Bundle\BusinessUnitBundle\Entity\BusinessUnit

    ds_business_unit.filter.business_unit.search:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            -
                id: exact
                uuid: exact
                owner: exact
                ownerUuid: exact
        tags:
            - { name: api_platform.filter, id: ds.business_unit.search }

    ds_business_unit.filter.business_unit.date:
        parent: api_platform.doctrine.orm.date_filter
        arguments:
            -
                createdAt: ~
                updatedAt: ~
                deletedAt: ~
        tags:
            - { name: api_platform.filter, id: ds.business_unit.date }
