parameters:
  env(APP_NAMESPACE): ''
  locale: en

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: ../src/{Controller,EventListener,Fixture,Repository,Service,Stat,Tenant,Validator}

  App\Controller\:
    resource: ../src/Controller
    tags: [controller.service_arguments]

  App\EventListener\Entity\Role\PropagationListener:
    tags:
      - { name: doctrine.event_listener, event: postPersist }
      - { name: doctrine.event_listener, event: postUpdate }
      - { name: doctrine.event_listener, event: preFlush }

  App\Fixture\:
    resource: ../src/Fixture
    tags: [doctrine.fixture.orm]

  App\Repository\AnonymousRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\Anonymous

  App\Repository\AnonymousPersonaRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\AnonymousPersona

  App\Repository\AnonymousRoleRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\AnonymousRole

  App\Repository\BusinessUnitRoleRepository:
      factory: ['@doctrine.orm.default_entity_manager', getRepository]
      arguments:
          - App\Entity\BusinessUnitRole

  App\Repository\BusinessUnitRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\BusinessUnit

  App\Repository\IndividualRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\Individual

  App\Repository\IndividualPersonaRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\IndividualPersona

  App\Repository\IndividualRoleRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\IndividualRole

  App\Repository\OrganizationRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\Organization

  App\Repository\OrganizationPersonaRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\OrganizationPersona

  App\Repository\OrganizationRoleRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\OrganizationRole

  App\Repository\RoleRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\Role

  App\Repository\StaffRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\Staff

  App\Repository\StaffPersonaRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\StaffPersona

  App\Repository\StaffRoleRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\StaffRole

  App\Repository\SystemRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\System

  App\Repository\SystemRoleRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\SystemRole

  App\Service\RoleService:
    public: true # Used by event listener
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@Ds\Component\Api\Api\Api'
      - '@Ds\Component\Discovery\Repository\ServiceRepository'
      - '%env(resolve:APP_NAMESPACE)%'

  App\Stat\Anonymous\CountStat:
    tags:
      - { name: ds_statistic.stat, alias: anonymous.count }

  App\Stat\Individual\CountStat:
    tags:
      - { name: ds_statistic.stat, alias: individual.count }

  App\Stat\Organization\CountStat:
    tags:
      - { name: ds_statistic.stat, alias: organization.count }

  App\Stat\Staff\CountStat:
    tags:
      - { name: ds_statistic.stat, alias: staff.count }

  App\Tenant\Loader\AclLoader:
    tags:
      - { name: ds_tenant.loader }

  App\Tenant\Loader\ConfigLoader:
    tags:
      - { name: ds_tenant.loader }

  App\Tenant\Loader\BusinessUnitLoader:
    tags:
      - { name: ds_tenant.loader, priority: -1 }

  App\Tenant\Loader\RoleLoader:
    tags:
      - { name: ds_tenant.loader, priority: -1 }

  App\Tenant\Loader\Identity\StaffLoader:
    tags:
      - { name: ds_tenant.loader }

  App\Tenant\Loader\Identity\StaffPersonaLoader:
    tags:
      - { name: ds_tenant.loader, priority: 2 }

  App\Tenant\Loader\Identity\StaffRoleLoader:
    tags:
      - { name: ds_tenant.loader, priority: 2 }

  App\Tenant\Loader\Identity\SystemLoader:
    tags:
      - { name: ds_tenant.loader }

  App\Tenant\Unloader\AnonymousPersonaUnloader:
    tags:
      - { name: ds_tenant.unloader, priority: -1 }

  App\Tenant\Unloader\AnonymousRoleUnloader:
    tags:
      - { name: ds_tenant.unloader, priority: -1 }

  App\Tenant\Unloader\AnonymousUnloader:
    tags:
      - { name: ds_tenant.unloader }

  App\Tenant\Unloader\BusinessUnitUnloader:
    tags:
      - { name: ds_tenant.unloader }

  App\Tenant\Unloader\IndividualPersonaUnloader:
    tags:
      - { name: ds_tenant.unloader, priority: -1 }

  App\Tenant\Unloader\IndividualRoleUnloader:
    tags:
      - { name: ds_tenant.unloader, priority: -1 }

  App\Tenant\Unloader\IndividualUnloader:
    tags:
      - { name: ds_tenant.unloader }

  App\Tenant\Unloader\OrganizationPersonaUnloader:
    tags:
      - { name: ds_tenant.unloader, priority: -1 }

  App\Tenant\Unloader\OrganizationRoleUnloader:
    tags:
      - { name: ds_tenant.unloader, priority: -1 }

  App\Tenant\Unloader\OrganizationUnloader:
    tags:
      - { name: ds_tenant.unloader }

  App\Tenant\Unloader\RoleUnloader:
    tags:
      - { name: ds_tenant.unloader }

  App\Tenant\Unloader\StaffPersonaUnloader:
    tags:
      - { name: ds_tenant.unloader, priority: -1 }

  App\Tenant\Unloader\StaffRoleUnloader:
    tags:
      - { name: ds_tenant.unloader, priority: -1 }

  App\Tenant\Unloader\StaffUnloader:
    tags:
      - { name: ds_tenant.unloader }

  App\Tenant\Unloader\SystemUnloader:
    tags:
      - { name: ds_tenant.unloader }

  App\Tenant\Unloader\SystemRoleUnloader:
    tags:
      - { name: ds_tenant.unloader, priority: -1  }

  App\Validator\Constraints\Role\Permissions\ValidValidator:
    tags:
      - { name: validator.constraint_validator }
