services:
    ds_anonymous.service.anonymous:
        class: Ds\Bundle\AnonymousBundle\Service\AnonymousService
        arguments:
            - '@doctrine.orm.entity_manager'
            - Ds\Bundle\AnonymousBundle\Entity\Anonymous

    ds_anonymous.service.anonymous_persona:
        class: Ds\Bundle\AnonymousBundle\Service\AnonymousPersonaService

    ds_anonymous.filter.anonymous.search:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            -
                id: exact
                uuid: exact
                owner: exact
                ownerUuid: exact
        tags:
            - { name: api_platform.filter, id: ds.anonymous.search }

    ds_anonymous.filter.anonymous.date:
        parent: api_platform.doctrine.orm.date_filter
        arguments:
            -
                createdAt: ~
                updatedAt: ~
                deletedAt: ~
        tags:
            - { name: api_platform.filter, id: ds.anonymous.date }

    ds_anonymous.filter.anonymous_persona.search:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            -
                id: exact
                uuid: exact
                owner: exact
                ownerUuid: exact
        tags:
            - { name: api_platform.filter, id: ds.anonymous_persona.search }

    ds_anonymous.filter.anonymous_persona.date:
        parent: api_platform.doctrine.orm.date_filter
        arguments:
            -
                createdAt: ~
                updatedAt: ~
                deletedAt: ~
        tags:
            - { name: api_platform.filter, id: ds.anonymous_persona.date }
