ds_security:
    acl:
        permissions:
            staff:             { entity: Ds\Bundle\StaffBundle\Entity\Staff, attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
            staff_field:       { field:  Ds\Bundle\StaffBundle\Entity\Staff.*, attributes: [BROWSE, READ, EDIT] }
