parameters:
    _staff: Ds\Bundle\StaffBundle\Entity\Staff

ds_security:
    permissions:
        staff:               { title: Staff,         entity: '%_staff%',              attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        staff_field:         { title: All Fields,    field:  '%_staff%.*',            attributes: [BROWSE, READ, EDIT] }
        staff_id:            { title: ID,            field:  '%_staff%.id',           attributes: [BROWSE, READ, EDIT] }
        staff_uuid:          { title: UUID,          field:  '%_staff%.uuid',         attributes: [BROWSE, READ, EDIT] }
        staff_created_at:    { title: Created At,    field:  '%_staff%.createdAt',    attributes: [BROWSE, READ, EDIT] }
        staff_updated_at:    { title: Updated At,    field:  '%_staff%.updatedAt',    attributes: [BROWSE, READ, EDIT] }
        staff_deleted_at:    { title: Deleted At,    field:  '%_staff%.deletedAt',    attributes: [BROWSE, READ, EDIT] }
        staff_owner:         { title: Owner,         field:  '%_staff%.owner',        attributes: [BROWSE, READ, EDIT] }
        staff_owner_uuid:    { title: Owner UUID,    field:  '%_staff%.ownerUuid',    attributes: [BROWSE, READ, EDIT] }
