services:
    ds_staff.service.staff:
        class: Ds\Bundle\StaffBundle\Service\StaffService
        arguments:
            - '@doctrine.orm.entity_manager'
            - Ds\Bundle\StaffBundle\Entity\Staff

    ds_staff.service.staff_persona:
        class: Ds\Bundle\StaffBundle\Service\StaffPersonaService

    ds_staff.filter.staff.search:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            -
                id: exact
                uuid: exact
                owner: exact
                ownerUuid: exact
        tags:
            - { name: api_platform.filter, id: ds.staff.search }

    ds_staff.filter.staff.date:
        parent: api_platform.doctrine.orm.date_filter
        arguments:
            -
                createdAt: ~
                updatedAt: ~
                deletedAt: ~
        tags:
            - { name: api_platform.filter, id: ds.staff.date }

    ds_staff.filter.staff_persona.search:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            -
                id: exact
                uuid: exact
                owner: exact
                ownerUuid: exact
        tags:
            - { name: api_platform.filter, id: ds.staff_persona.search }

    ds_staff.filter.staff_persona.date:
        parent: api_platform.doctrine.orm.date_filter
        arguments:
            -
                createdAt: ~
                updatedAt: ~
                deletedAt: ~
        tags:
            - { name: api_platform.filter, id: ds.staff_persona.date }
