services:
    ds_persona.service.persona:
        class: Ds\Bundle\PersonaBundle\Service\PersonaService

    ds_persona.filter.persona:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            - { uuid: exact }
        tags:
            - { name: api_platform.filter, id: ds_persona.filter.persona }
