objects:
  - staff: '%identity.admin.uuid%'

prototype:
  staff: ~
  uuid: ~
  owner: BusinessUnit
  owner_uuid: '%business_unit.administration.uuid%'
  title:
    en: Default
  data: {}
  tenant: '%tenant.uuid%'
