objects:
  - staff: '%identity.admin.uuid%'
    role: '%role.administrator.uuid%'

prototype:
  staff: ~
  owner: BusinessUnit
  owner_uuid: '%business_unit.administration.uuid%'
  role: ~
  entity_uuids: []
  tenant: '%tenant.uuid%'
