parameters:
    _individual: Ds\Bundle\IndividualBundle\Entity\Individual

ds_security:
    permissions:
        individual:               { title: Individual,    entity: '%_individual%',              attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        individual_field:         { title: All Fields,    field:  '%_individual%.*',            attributes: [BROWSE, READ, EDIT] }
        individual_id:            { title: ID,            field:  '%_individual%.id',           attributes: [BROWSE, READ, EDIT] }
        individual_uuid:          { title: UUID,          field:  '%_individual%.uuid',         attributes: [BROWSE, READ, EDIT] }
        individual_created_at:    { title: Created At,    field:  '%_individual%.createdAt',    attributes: [BROWSE, READ, EDIT] }
        individual_updated_at:    { title: Updated At,    field:  '%_individual%.updatedAt',    attributes: [BROWSE, READ, EDIT] }
        individual_deleted_at:    { title: Deleted At,    field:  '%_individual%.deletedAt',    attributes: [BROWSE, READ, EDIT] }
        individual_owner:         { title: Owner,         field:  '%_individual%.owner',        attributes: [BROWSE, READ, EDIT] }
        individual_owner_uuid:    { title: Owner UUID,    field:  '%_individual%.ownerUuid',    attributes: [BROWSE, READ, EDIT] }
