ds_security:
    acl:
        permissions:
            individual:             { entity: Ds\Bundle\IndividualBundle\Entity\Individual, attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
            individual_field:       { field:  Ds\Bundle\IndividualBundle\Entity\Individual.*, attributes: [BROWSE, READ, EDIT] }
