services:
    ds_individual.service.individual:
        class: Ds\Bundle\IndividualBundle\Service\IndividualService

    ds_individual.filter.individual:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            - { uuid: exact }
        tags:
            - { name: api_platform.filter, id: ds_individual.filter.individual }
