parameters:
    _admin: Ds\Bundle\AdminBundle\Entity\Admin

ds_security:
    permissions:
        admin:               { title: Admin,         entity: '%_admin%',              attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        admin_field:         { title: All Fields,    field:  '%_admin%.*',            attributes: [BROWSE, READ, EDIT] }
        admin_id:            { title: ID,            field:  '%_admin%.id',           attributes: [BROWSE, READ, EDIT] }
        admin_uuid:          { title: UUID,          field:  '%_admin%.uuid',         attributes: [BROWSE, READ, EDIT] }
        admin_created_at:    { title: Created At,    field:  '%_admin%.createdAt',    attributes: [BROWSE, READ, EDIT] }
        admin_updated_at:    { title: Updated At,    field:  '%_admin%.updatedAt',    attributes: [BROWSE, READ, EDIT] }
        admin_deleted_at:    { title: Deleted At,    field:  '%_admin%.deletedAt',    attributes: [BROWSE, READ, EDIT] }
        admin_owner:         { title: Owner,         field:  '%_admin%.owner',        attributes: [BROWSE, READ, EDIT] }
        admin_owner_uuid:    { title: Owner UUID,    field:  '%_admin%.ownerUuid',    attributes: [BROWSE, READ, EDIT] }
